alleyinteractive/wordpress-fieldmanager

php/class-fieldmanager-field.php
php/class-fieldmanager-group.php
php/context/class-fieldmanager-context-post.php
php/context/class-fieldmanager-context-quickedit.php
php/context/class-fieldmanager-context-submenu.php
php/context/class-fieldmanager-context-term.php
php/context/class-fieldmanager-context-user.php
php/context/class-fieldmanager-context.php
tests/php/test-fieldmanager-autocomplete-field.php
tests/php/test-fieldmanager-checkbox-field.php
tests/php/test-fieldmanager-context-post.php
tests/php/test-fieldmanager-context-quickedit.php
tests/php/test-fieldmanager-context-submenu.php
tests/php/test-fieldmanager-context-term.php
tests/php/test-fieldmanager-context-user.php
tests/php/test-fieldmanager-datasource-post.php
tests/php/test-fieldmanager-datasource-term.php
tests/php/test-fieldmanager-datepicker-field.php
tests/php/test-fieldmanager-group.php
tests/php/test-fieldmanager-richtextarea-field.php
tests/php/test-fieldmanager-term-meta.php
tests/php/test_fieldmanager_field.php

This PR is a work in progress and aims to resolve #14.
This update adds an option `$serialize_data` to `Fieldmanager_Field` to specify if that element should store its data serialized (the default) or unserialized (that is, using individual meta keys). This can be applied to a single repeating field, where the field is stored with duplicate keys, or to a group where each child gets its own key. In the case of a group, the field is prefixed with the group's name and an underscore. This update adds another option `$add_to_prefix` to `Fieldmanager_Group` allowing you the choice of whether or not to add that group's name to the prefix (`true` by default), which means you can completely separate your data structure from its presentation.
Groups can be nested any number of levels deep, and …

Add support for individual meta keys

---

fieldmanager.php
tests/php/bootstrap.php
tests/php/test-fieldmanager-calculate-context.php

There are a few parts to this PR:
* 2f0d1d8, which makes sure that all FM submenus hooked at priority 10 are added
* b7c2645, which is the attempted fix for #260 
* bab112d and 982adfe, which introduce a function and tests for calculating the FM context
* 87434f1, which stops `fm_trigger_context_action()` from firing an action of `fm_`

Submenu contexts for custom menus; submenu context test

---

php/util/class-fieldmanager-util-term-meta.php

Although this post type is private, the label still appears on the Export page, because `$can_export` is not false, and it might appear elsewhere.
Without its own label, the post type is labeled "Pages."

Add a label to the term meta post type

---

php/context/class-fieldmanager-context-page.php

I think this is going to be superseded by https://github.com/alleyinteractive/wordpress-fieldmanager/pull/157, but in the meantime I just want to fix this little bug so that I can update FM to the latest on an old project that uses `Fieldmanager_Context_Page`.

fixed misnamed class for Fieldmanager_Context_Page

---

js/fieldmanager-autocomplete.js
php/class-fieldmanager-autocomplete.php
php/datasource/class-fieldmanager-datasource-post.php
php/datasource/class-fieldmanager-datasource-term.php
php/datasource/class-fieldmanager-datasource-user.php

This adds a new parameter called `custom_args` that lets you create a handler that can append arbitrary data to an AJAX request. The assumption is that if you wanted to use it in a query, you would also implement your own `query_callback` for the datasources that support that. It's otherwise harmless and ignored.

Adding custom args to autcomplete ajax requests

---

js/fieldmanager.js

For radio buttons `trigger.val();` returns the first element’s value, not the checked element’s value. This PR adds a check to see if there is a checked value when the trigger initializes.
#264 has a related check for checkboxes.

Display If: Match the checked value on load

---

php/util/class-fieldmanager-util-term-meta.php

After #319, the term meta post type falls back to the default `rewrite => true`, which generates unused (I think) rewrite rules.

Remove term meta rewrite rules

---

php/class-fieldmanager-media.php

`Fieldmanager_Media::__construct()` was defining an action as a closure, which makes it so that `wp_filters` isn't serializable. This pull request moves the action into a class function instead.

Fix for serializable wp_filters

---

fieldmanager.php
php/context/class-fieldmanager-context-submenu.php
tests/php/test-fieldmanager-calculate-context.php

A simpler alternative to #368. This _only_ supports post_type as a second query arg in the URL, but as far as I can tell, that's all core supports as well.
Resolves #195

Allow post_type to be in url for submenu pages

---

php/datasource/class-fieldmanager-datasource-term.php
tests/php/test-fieldmanager-datasource-term.php

* Fix a data type issue introduced in core, because `null !== ''` (see #386 for further details; this resolves #386)
* Ensure any taxonomy used in a datasource, where the data is stored as a term relationship, is sortable

Bug fixes for term datasource

---

js/media/fieldmanager-media.js
php/class-fieldmanager-media.php
tests/php/test-fieldmanager-media-field.php
tests/php/test-fieldmanager-script-loading.php

This fixes a bug where repeatable media fields would show the wrong preview size for newly-created fields. Also, adds basic unit tests for rendering and saving.

Fix repeatable media field preview sizes

---

php/context/class-fieldmanager-context-quickedit.php

This fixes the issue described in #341. 
Exiting after outputting the desired ajax response prevents WordPress from spitting out its ugly zeroes.

Remove errant "0" from ajax response in quickedit context

---

tests/php/test_fieldmanager_field.php

These broke in #419, but the bug in #421 prevented Travis from reporting it.
Note that Travis will still fail on the latest nightly builds of core, due to a recent core update surrounding richtextareas.

Fix unit tests for multi tool labels

---

php/class-fieldmanager-options.php

`Fieldmanager_Options::$sanitize` was defined as a closure, which means that objects of this class are not serializable. This commit makes `$sanitize` a regular function.
This is similar to #357, and also alleyinteractive/fm-zones#3

Make `Fieldmanager_Options::$sanitize` a non-closure function

---

php/context/class-fieldmanager-context-submenu.php
tests/php/test-fieldmanager-context-submenu.php

See https://make.wordpress.org/core/2015/07/31/headings-in-admin-screens-change-in-wordpress-4-3/. Fixes #383.

Use <h1> for submenu headings

---

css/fieldmanager-group-tabs.css
css/fieldmanager.css
js/fieldmanager.js
php/class-fieldmanager-field.php
php/class-fieldmanager-group.php

* adds a hover state to field group handlers
* collapsible toggler added to collapsible fields
* aria-expanded attribute added to the collapsible toggler

fields ui modifications

---

fieldmanager.php

Since https://core.trac.wordpress.org/changeset/36308, the link for editing a term is `term.php`, not `edit-tags.php?action=edit`. This looks for that screen context when calculating Fieldmanager context values.
Fixes #433.

Recognize term.php as context for "term"

---

php/context/class-fieldmanager-context-storable.php
php/datasource/class-fieldmanager-datasource-term.php
tests/php/test-fieldmanager-datasource-term.php

When a Term datasource is a part of a repeatable group, the expected behavior is to save all terms present in all groups, not just the term of the last group. By passing `$append = true` after the first save, we can ensure subsequent terms maintain their relationship to the post.
Fixes #356

Pass `$append = true` after first save when datasource repeats

---

php/class-fieldmanager-field.php

Defaults to `true`. `false` places it before the element.
Fixes #102

Use `$field->description_after_element` to control description position

---

php/class-fieldmanager-autocomplete.php
php/class-fieldmanager-group.php
php/class-fieldmanager-options.php
tests/php/test-fieldmanager-datasource-term.php

361 only save to taxo

---

php/context/class-fieldmanager-context-submenu.php
tests/php/test-fieldmanager-context-submenu.php

Submenu context should respect `skip_save` on its fields

---

js/fieldmanager-group-tabs.js

Previously, the click events would only be bound on $(document).ready(),
leaving dynamically added groups without bound events.
Fixes #392

Properly bind tab button click events for new tabbed groups

---

.travis.yml

PHP7 is fully supported by WordPress core, it should be fully supported by fieldmanager

remove php7 from allowed failures

---

js/fieldmanager-autocomplete.js
js/fieldmanager.js
tests/js/index.html
tests/js/test-fieldmanager.js

This combines effort and notes from several previous reports and PRs: #243, #415, #418, #435, #264, #324. It attempts to focus on bugs fixed in that work but leaves out some enhancements for post-1.0. 
- Allow numeric values to be used as the display-if 'value'
- Allow checkboxes to be used as display-if triggers
- Allow autocompletes to be used as display-if triggers
- Improve some cases of handling field visibility on load
Closes #243, fixes #242, closes #415, fixes #435, closes #264, fixes #405, fixes #241.

Address some buggy display-if cases

---

php/class-fieldmanager-group.php

From the docs: "Selects all input, textarea, select and button elements." Fixes #397.

Target :input, not .input, in label macros

---

php/class-fieldmanager-colorpicker.php
tests/php/test-fieldmanager-colorpicker-field.php

Allows developers to supply a new option `default_color` to specify whether or not the color picker will use the clear or default functionality.
From https://github.com/alleyinteractive/wordpress-fieldmanager/issues/490

Adds a default color

---

php/class-fieldmanager-options.php

This is a breaking change, but it was implemented wrong in the beginning. It's very rarely used, so I think it's safe to merge this.

Fix argument order for optgroup key=>val pairs

---

.travis.yml

The way that Travis was testing phpunit, only the result of qunit indicated that the job passed or failed

Fix bug in travis config, update WP

---

php/class-fieldmanager-datepicker.php
php/class-fieldmanager-textarea.php
phpcs.ruleset.xml

PHPCS for TextArea and Datepicker

---

php/util/class-fieldmanager-util-assets.php

The docs I added in #522 contained several mistakes, fixed (I hope) here.

Fix `@var` and missing variable in filter docs

---

tests/php/test-fieldmanager-context-term-fm-term-meta.php
tests/php/test-fieldmanager-context-term.php

after https://core.trac.wordpress.org/changeset/39626; split from #565.

Fix missing `parent::tearDown()`s

---

.travis.yml
bin/install-wp-tests.sh
php/util/class-fieldmanager-util-term-meta.php
phpcs.ruleset.xml

Fix PHPUnit incompatibilities, update variable assignment

---

.travis.yml

WordPress core has not allowed its tests to fail on PHP 7.1 [since December 2016](https://core.trac.wordpress.org/changeset/39424). Accordingly, this requires Fieldmanager to run against 7.1 per the reasoning in #462.

Test against PHP 7.1 in Travis

---

php/class-fieldmanager-draggablepost.php
phpcs.ruleset.xml

#271 
Adhere to PHPCS for this file.
- `/php/class-fieldmanager-draggablepost.php`

PHPCS: /php/class-fieldmanager-draggablepost.php

---

php/context/class-fieldmanager-context-post.php
php/context/class-fieldmanager-context-quickedit.php
php/context/class-fieldmanager-context-storable.php
php/context/class-fieldmanager-context-submenu.php
php/context/class-fieldmanager-context-term.php
php/context/class-fieldmanager-context-user.php
tests/php/test-fieldmanager-context-storable.php

Replaces #617, props @david-binda

Cast scalar meta values as string

---

php/datasource/class-fieldmanager-datasource-term.php

When `$only_save_to_taxonomy` is set to true, some errors can occur. `get_the_terms()` can return false when creating a new post. This (when passed to `usort()` throws an error since it's not an array.
We should not use the return value of  `usort() ` as it sorts the array by reference.

Fix issues with only_save_to_taxonomy

---

php/class-fieldmanager-colorpicker.php
php/context/class-fieldmanager-context-quickedit.php
php/datasource/class-fieldmanager-datasource-post.php
php/datasource/class-fieldmanager-datasource-term.php

Also closes #492, as that method needed a phpcs update so I instead opted to use core's `sanitize_hex_color()`.

Updates per latest phpcs standards

---

fieldmanager.php
js/fieldmanager.js
package.json
php/class-fieldmanager-field.php

Also includes a version bump; this will push out as 1.2.1.

Fix a bug where checkboxes trigger displayif

---

php/datasource/class-fieldmanager-datasource-term.php
tests/php/test-fieldmanager-datasource-term.php

Get datasource terms with `'orderby' => 'term_order'`

---

php/util/class-fieldmanager-util-validation.php

I have a field with these validation rules:
```
'validation_rules'   => ['required' => true, 'min' => 1]
```
and I wanted to customise the error message for the `min` rule not being met, which I tried with
```
'validation_messages' => [
'min' => 'You must select an image'
]
```
which did not work, and gave me this warning:
```
Warning: Illegal string offset 'min' in /vagrant/wordpress/plugins/fieldmanager/php/util/class-fieldmanager-util-validation.php on line 172
```
Investigating `class-fieldmanager-util-validation.php` showed that `$messages` is initialised as a string, but if `$fm->validation_rules` is not a string the code tries to treat `$messages` as an associative array.

Reinit $messages as an array if validation_rules is not a string

---

php/class-fieldmanager-datepicker.php
tests/php/test-fieldmanager-datepicker-field.php

Since I don't have write access to ravatparmar's fork of this repo, I am merging in his change here. 
See https://github.com/alleyinteractive/wordpress-fieldmanager/pull/724

Fix date displaying wrong if it's before 1970s

---

.travis.yml
fieldmanager.php
js/fieldmanager-autocomplete.js
js/fieldmanager-colorpicker.js
js/fieldmanager-datepicker.js
js/fieldmanager-draggablepost.js
js/fieldmanager-group-tabs.js
js/fieldmanager-loader.js
js/fieldmanager-post.js
js/fieldmanager-quickedit.js
js/fieldmanager-select.js
js/fieldmanager.js
js/grid.js
js/richtext.js
package.json
php/class-fieldmanager-autocomplete.php
php/class-fieldmanager-colorpicker.php
php/class-fieldmanager-datepicker.php
php/class-fieldmanager-draggablepost.php
php/class-fieldmanager-field.php
php/class-fieldmanager-grid.php
php/class-fieldmanager-group.php
php/class-fieldmanager-media.php
php/class-fieldmanager-options.php
php/class-fieldmanager-richtextarea.php
php/class-fieldmanager-select.php
php/context/class-fieldmanager-context-quickedit.php
php/util/class-fieldmanager-util-assets.php
tests/php/test-fieldmanager-script-loading.php

Fixes issues with Fieldmanager fields, which require JavaScript hooks, not initializing properly when Gutenberg is active. `wp.domReady` fires later than jQuery's `document.ready`, so this, combined with moving most FM scripts to the footer, should resolve race conditions that prevent initialization of dynamic fields across the board in Fieldmanager.
Additionally, uses `FM_VERSION` to set version numbers for Fieldmanager JS and CSS to ensure cache busting when shipping a new version of Fieldmanager to aggressively cached sites, such as VIP Go. Accordingly, bumps the version to 1.2.5.
Finally, moves script load for most FM scripts to the footer, which is required for proper initialization of fields in a Gutenberg context, and is generally a best practice. This move should not break …

Use the new wp.domReady helper if it is available

---

fieldmanager.php
package.json

- Identical to v1.2.5, except instead of using the `-beta2` suffix (which was used for cache busting on VIP Go during version testing) it now uses an updated version number.

Bump version number to 1.2.6

---

fieldmanager.php
package.json
php/class-fieldmanager-field.php
php/context/class-fieldmanager-context-menuitem.php
tests/php/test-fieldmanager-context-menuitem.php

Adds a new context for menu items since a hook as been added into core to make this possible - https://github.com/WordPress/WordPress/blob/26bda18a23174afb048afbe62296c76a62add542/wp-admin/includes/class-walker-nav-menu-edit.php#L242

Add Menu Item Context

---

php/datasource/class-fieldmanager-datasource-post.php
php/datasource/class-fieldmanager-datasource-term.php
php/datasource/class-fieldmanager-datasource-user.php
php/datasource/class-fieldmanager-datasource.php

Addresses https://github.com/alleyinteractive/wordpress-fieldmanager/issues/621

Adds the calling class to the string for the ajax hash to prevent collisions

---

js/fieldmanager-autocomplete.js
js/fieldmanager-datepicker.js

Closes #793.
- Allows Autocomplete and Date fields in Gutenberg to load jQuery scripts on input focus. In the Gutenberg context fields are not enabled as the jQuery `$( 'FIELD_NAME:visible' )` returns undefined, unless re-initialized as needed which prevents the need to auto-enabled ALL fields on the page (many of which are hidden by default using the `display_if` option).

DateField/AutoComplete Gutenberg Patch

---

php/class-fieldmanager-grid.php
tests/php/test-fieldmanager-script-loading.php

Grid has received little attention since its introduction and today appears to be nonfunctional -- see #789. Additionally, Handsontable, on which it is based, is now a commercial product. We can no longer recommend it and so now move to deprecate it with intent to remove it from the repository.

Deprecate `Fieldmanager_Grid`

---

js/fieldmanager-loader.js

This backports the fix in 0bf49fb0f3 to the 1.3 branch.
See #815.

Fix FM module loader in Gutenberg context

---

js/fieldmanager-loader.js

This is a followup to 754f101e to make sure that we wait for the `.metabox-location-normal` form to be moved into `.edit-post-meta-boxes-area__container` in the block editor before running our loading callbacks. Otherwise, there is the possibility that the callbacks will still fire too early, before the FM forms are ready.

Loader: Fix loader callback timing

---

js/fieldmanager.js

The performance regression from 1.3 → 1.4 was due to this traversal:
```js
$( '.fm-element[name^="fmtemp_"], .fm-incrementable[name^="fmtemp_"]' ).each( ... )
```
Since the script knows which elements it changed, this update stores a reference to each changed element to avoid the later DOM traversal.
While this fixes the regression from 1.3 → 1.4, `fm_renumber()`﻿is still very slow at scale because of all the DOM traversal. A significant refactor is in order.
Resolves #827
---
For posterity, here's some sample code to produce a very slow experience adding and sorting...
```php
add_action(
'init',
function() {
register_post_type(
'demo',
[
'labels'   => [ 'name' => 'Demos' ],
'public'   => false,
'show_ui'  => true,
'supports' => [ 'title' ],
]
);
}
);
add_action(
'fm_post_demo', …
```

Fix performance regression in fm_renumber

---

php/context/class-fieldmanager-context-term.php
php/context/class-fieldmanager-context.php
tests/php/test-fieldmanager-context-term.php

Protect against side effect term updates

---

php/context/class-fieldmanager-context.php

This action allows other plugins such as https://github.com/alleyinteractive/fm-gutenberg to perform an action when a FieldManager context is constructed.

adds action

---

php/class-fieldmanager-autocomplete.php
tests/php/test-fieldmanager-autocomplete-field.php

This resolves https://github.com/alleyinteractive/wordpress-fieldmanager/issues/839
I am adding a test along with this patch. Without this patch, the test will fail, as pictured:

PHP 8.0: Autocomplete field with Extra Element causes Array to String Conversion Warning

---

.github/workflows/phpcs.yml
.github/workflows/phpunit.yml
composer.json

- Replaces set-output with GITHUB_OUTPUT to fix the deprecation: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Move the phpcs action to the shared action for the organization.

Replacing set-output with GITHUB_OUTPUT, moving to shared PHPCS configuration

---

php/class-fieldmanager-textarea.php
tests/php/bootstrap.php
tests/php/includes/class-fieldmanager-deprecation-exception.php
tests/php/test-fieldmanager-textarea-field.php

Note: To minimize the impact on the rest of the Fieldmanager fields, this change is localized to the TextArea field, since that appears to be where the issue is occurring.
[PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated](https://github.com/alleyinteractive/wordpress-fieldmanager/issues/863)
To address the issue of PHP deprecation errors when a `default_value` field is not set and defaults to `null`, we have modified the logic in the printing of fields within the WP admin area. Specifically, in scenarios where a default value is not set, which leads to a `null` return value, a ternary operation or a direct assignment now ensures that `esc_textarea` receives an empty string instead of `null`. This change prevents `htmlspecialchars()` …

Issue-863: PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated

---

php/class-fieldmanager-autocomplete.php
php/class-fieldmanager-colorpicker.php
php/class-fieldmanager-datepicker.php
php/class-fieldmanager-draggablepost.php
php/class-fieldmanager-field.php
php/class-fieldmanager-grid.php
php/class-fieldmanager-group.php
php/class-fieldmanager-link.php
php/class-fieldmanager-media.php
php/class-fieldmanager-options.php
php/class-fieldmanager-password.php
php/class-fieldmanager-richtextarea.php
php/class-fieldmanager-select.php
php/class-fieldmanager-textarea.php
php/class-fieldmanager-textfield.php

This pull request updates class constructor docblocks to accurately reflect that `$label` can be either an `array` or a `string`. This change aims to address issues with code quality tools like `phpstan` that arise due to the current incorrect specification of `$label` as a string only. Fixes #867
Each constructor within the project has a `$label` parameter, which, according to the current docblocks, accepts only a string. This has been identified as incorrect since `$label` can also be an array. The mismatch between the implementation and the documentation causes tools like `phpstan` to report errors, potentially affecting code quality assurance processes.
- Updated the docblocks across various constructors to specify that `$label` can be either a `string` or an `array`.
- Ensured that …

Issue-867: Update class constructor docblocks to support specifying an `array` or a `string` for `$label`
