alleyinteractive/wordpress-fieldmanager

- php/util/class-fieldmanager-util-term-meta.php
* phpdoc
* update methods to always return post meta functions
* coding standards
> Term Meta cleanup

- php/class-fieldmanager-select.php
- tests/php/test-fieldmanager-select-field.php
Also adds basic tests for select fields. Requires #255, so this is a placeholder until that gets merged.
Closes #150.
> Force first_empty for repeatable selects

- php/datasource/class-fieldmanager-datasource-term.php
I get an undefined variable notice if no terms are found.
> fix undefined variable

- fieldmanager.php
- php/context/class-fieldmanager-context-submenu.php
- tests/php/test-fieldmanager-context-submenu.php
Closes #314; addresses bug introduced in bdb9b82
> Fix bug with submenu slashes

- php/util/class-fieldmanager-util-term-meta.php
Replaces #318, closes #317. Props @jjeaton
> Remove unnecessary post type args

- templates/datepicker.php
Addresses https://github.com/alleyinteractive/wordpress-fieldmanager/issues/365
> add fm-element class to am/pm select

- js/fieldmanager-group-tabs.js
- php/class-fieldmanager-group.php
> Turn active tab persistent to a Group option, defaulting to true

- .travis.yml
- Gruntfile.js
- README.md
- package.json
- tests/js/index.html
- tests/js/test-fieldmanager.js
- tests/js/vendor/qunit-1.19.0.css
- tests/js/vendor/qunit-1.19.0.js
This would add a basic infrastructure for adding and running JS unit tests with QUnit. 
It could use a good look from anyone with some QUnit experience. I'm sure a lot of it could be improved, now or later, such as relying on the `develop` repository and the "script loader" in `index.html`.
> Add QUnit tests

- js/media/fieldmanager-media.js
- php/class-fieldmanager-media.php
- tests/php/test-fieldmanager-media-field.php
> Merge mime_type param

- php/context/class-fieldmanager-context-quickedit.php
Travis will still fail due to other issues, but this needs to be merged before fixing those.
> Fix quickedit unit tests

- php/datasource/class-fieldmanager-datasource-user.php
- tests/php/test-fieldmanager-datasource-user.php
> Add wildcards to get_users search

- php/class-fieldmanager-group.php
- tests/php/test-fieldmanager-group.php
> accommodate fields with literal string value "0" and add test

- css/fieldmanager.css
- fieldmanager.php
> Remove RTA border to soften FOUC

- php/class-fieldmanager-group.php
- tests/php/test-fieldmanager-group.php
> honor $skip_save for child elements inside groups

- php/class-fieldmanager-options.php
> Define custom `sanitize` callback early, to allow override by `$options`

- php/class-fieldmanager-autocomplete.php
- tests/php/test-fieldmanager-datasource-term.php
> Allow saving taxonomy data to users

- php/class-fieldmanager-options.php
- tests/php/test-fieldmanager-checkboxes-field.php
- tests/php/test-fieldmanager-radios-field.php
- tests/php/test-fieldmanager-select-field.php
I believe that this is an appropriate fix for #352, @mboynes please sanity check me?
> fix handling for repeatable multiple select fields #352

- js/fieldmanager.js
> When an element is dynamically added, update its label's `for` too

- js/grid.js
- php/class-fieldmanager-grid.php
> JS refactor to support grid serialization on multiple grid adds

- php/class-fieldmanager-autocomplete.php
- php/class-fieldmanager-field.php
- php/class-fieldmanager-group.php
- php/class-fieldmanager-options.php
- php/datasource/class-fieldmanager-datasource-post.php
- tests/php/test-fieldmanager-datasource-post.php
Closes #307, closes #284, refs #18, resolves #283
> Address several bugs with save_to_post_parent

- css/fieldmanager-group-tabs.css
Removes box shadow and border on vertical tabs. Resolves #471
> 471 vertical tab border and box shadow

- css/fieldmanager.css
increases datepicker time field for issue #472
> #472 increase to datepicker time field

- js/fieldmanager.js
> Update label for attr in incrementable options

- fieldmanager.php
- php/class-fieldmanager-autocomplete.php
- php/class-fieldmanager-group.php
- php/class-fieldmanager-media.php
- php/class-fieldmanager-richtextarea.php
- php/class-fieldmanager-select.php
Official 1.0.0 release.
Resolves #411.
> Bump the version UP

- php/class-fieldmanager-field.php
- php/class-fieldmanager-group.php
- tests/php/test-fieldmanager-group.php
- tests/php/test_fieldmanager_field.php
> Appropriately handle zeros in repeating fields

- css/fieldmanager.css
- php/class-fieldmanager-group.php
- tests/php/test-fieldmanager-group.php
Resolves #505, resolves alleyinteractive/fm-widgets#7
> Fix toggle arrow on collapsed groups

- fieldmanager.php
Reviewing this PR would benefit from `?w=1` in the URL, as it's mostly whitespace.
> Filter the calculated context for plugins

- fieldmanager.php
- php/util/class-fieldmanager-util-assets.php
> Document new hooks

- Gruntfile.js
- composer.json
- phpcs.ruleset.xml
> Require new files to pass PHPCS

- Gruntfile.js
- js/fieldmanager.js
- tests/js/index.html
- tests/js/test-fieldmanager.js
> Abandon display-if setup if no trigger is found

- php/class-fieldmanager-checkboxes.php
- php/class-fieldmanager-password.php
- phpcs.ruleset.xml
> PHPCS for Checkboxes and Password

- php/class-fieldmanager-media.php
- tests/php/test-fieldmanager-media-field.php
> Add selected/remove labels to `Fieldmanager_Media`

- fieldmanager.php
- phpcs.ruleset.xml
Abide by PHP WordPress Coding standards for this file 
- `/fieldmanager.php`
> PHPCS: /fieldmanager.php

- php/class-fieldmanager-checkbox.php
- phpcs.ruleset.xml
Adhere to PHPCS for this file.
- `/php/class-fieldmanager-checkbox.php`
> PHPCS: /php/class-fieldmanager-checkbox.php

- php/class-fieldmanager-autocomplete.php
- phpcs.ruleset.xml
Abide to PHP WordPress coding standards for this file.
- `/php/class-fieldmanager-autocomplete.php`
> PHPCS:  /php/class-fieldmanager-autocomplete.php

- php/class-fieldmanager-colorpicker.php
- phpcs.ruleset.xml
PHPCS for this file:
- `/php/class-fieldmanager-colorpicker.php`
> PHPCS:  /php/class-fieldmanager-colorpicker.php

- php/class-fieldmanager-field.php
- phpcs.ruleset.xml
Abide to PHPCS for this file:
- `/php/class-fieldmanager-field.php`
> PHPCS: /php/class-fieldmanager-field.php

- php/class-fieldmanager-grid.php
- phpcs.ruleset.xml
#271 
- `/php/class-fieldmanager-grid.php`
> PHPCS: /php/class-fieldmanager-grid.php

- php/class-fieldmanager-group.php
- phpcs.ruleset.xml
#271 
- `/php/class-fieldmanager-group.php`
> PHPCS: /php/class-fieldmanager-group.php

- php/class-fieldmanager-hidden.php
- phpcs.ruleset.xml
#271 
- `/php/class-fieldmanager-hidden.php`
> PHPCS: /php/class-fieldmanager-hidden.php

- php/class-fieldmanager-link.php
- phpcs.ruleset.xml
#271 
- `/php/class-fieldmanager-link.php`
> PHPCS: /php/class-fieldmanager-link.php

- php/class-fieldmanager-media.php
- phpcs.ruleset.xml
#271 
- `php/class-fieldmanager-media.php`
> PHPCS: php/class-fieldmanager-media.php

- php/class-fieldmanager-options.php
- phpcs.ruleset.xml
#271 
- `php/class-fieldmanager-options.php`
> PHPCS: php/class-fieldmanager-options.php

- php/class-fieldmanager-radios.php
- phpcs.ruleset.xml
#271 
PHPCS for file
- `php/class-fieldmanager-radios.php`
> PHPCS: php/class-fieldmanager-radios.php

- php/class-fieldmanager-richtextarea.php
- phpcs.ruleset.xml
#271 
- `php/class-fieldmanager-richtextarea.php`
> PHPCS: /php/class-fieldmanager-richtextarea.php

- php/class-fieldmanager-select.php
- phpcs.ruleset.xml
#271 
- `php/class-fieldmanager-select.php`
> PHPCS: /php/class-fieldmanager-select.php

- php/class-fieldmanager-textfield.php
- phpcs.ruleset.xml
#271 
- `php/class-fieldmanager-textfield.php`
> PHPCS: /php/class-fieldmanager-textfield.php

- php/context/class-fieldmanager-context-page.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-page.php`
> PHPCS: php/context/class-fieldmanager-context-page.php

- php/context/class-fieldmanager-context-post.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-post.php`
> PHPCS: php/context/class-fieldmanager-context-post.php

- php/context/class-fieldmanager-context-quickedit.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-quickedit.php`
> PHPCS: php/context/class-fieldmanager-context-quickedit.php

- php/context/class-fieldmanager-context-storable.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-storable.php`
> PHPCS: php/context/class-fieldmanager-context-storable.php

- php/context/class-fieldmanager-context-submenu.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-submenu.php`
> PHPCS: php/context/class-fieldmanager-context-submenu.php

- php/context/class-fieldmanager-context-term.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-term.php`
> PHPCS: php/context/class-fieldmanager-context-term.php

- php/context/class-fieldmanager-context-user.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context-user.php`
> PHPCS: php/context/class-fieldmanager-context-user.php

- php/context/class-fieldmanager-context.php
- phpcs.ruleset.xml
#271 
- `php/context/class-fieldmanager-context.php`
> PHPCS: php/context/class-fieldmanager-context.php

- php/datasource/class-fieldmanager-datasource-post.php
- phpcs.ruleset.xml
#271 
- `php/datasource/class-fieldmanager-datasource-post.php`
> PHPCS: php/datasource/class-fieldmanager-datasource-post.php

- php/datasource/class-fieldmanager-datasource-term.php
- phpcs.ruleset.xml
#271 
- `php/datasource/class-fieldmanager-datasource-term.php`
> PHPCS: php/datasource/class-fieldmanager-datasource-term.php

- php/datasource/class-fieldmanager-datasource-user.php
- phpcs.ruleset.xml
#271 
PHPCS for files:
- `php/datasource/class-fieldmanager-datasource-user.php`
> PHPCS: php/datasource/class-fieldmanager-datasource-user.php

- php/datasource/class-fieldmanager-datasource.php
- phpcs.ruleset.xml
- `php/datasource/class-fieldmanager-datasource.php`
> PHPCS: php/datasource/class-fieldmanager-datasource.php

- php/context/class-fieldmanager-context-page.php
- php/context/class-fieldmanager-context-post.php
- php/context/class-fieldmanager-context-submenu.php
- php/context/class-fieldmanager-context-term.php
- php/context/class-fieldmanager-context-user.php
- php/util/class-fieldmanager-util-validation.php
- phpcs.ruleset.xml
#271 
- `php/util/class-fieldmanager-util-validation.php`
> PHPCS: php/util/class-fieldmanager-util-validation.php

- php/context/class-fieldmanager-context-submenu.php
> Pass 'autoload' param to `update_option()` in `update_data()`

- js/fieldmanager.js
> Fix sortable bug with mixed sortable nested groups

- php/datasource/class-fieldmanager-datasource-post.php
- php/datasource/class-fieldmanager-datasource.php
- phpcs.ruleset.xml
- templates/options-checkboxes.php
- templates/options-radios.php
> Enable some nice-to-have PHPCS features

- js/fieldmanager.js
- php/class-fieldmanager-field.php
- tests/js/index.html
> Add and target prefixed class to initialize display-if fields

- php/class-fieldmanager-field.php
> Avoid attempting to count a non-countable value in PHP 7.2

- Gruntfile.js
- tests/js/index.html
> Use built core repo for JS tests

- .gitignore
- fieldmanager.php
- package.json
I will release this version once this is merged.
> increment version to 1.2.4

- apigen.neon
This is an innocuous change related to generating docs for api.fieldmanager.org.
> Update GA for api.fieldmanager.org

- php/class-fieldmanager-autocomplete.php
- php/class-fieldmanager-field.php
- php/class-fieldmanager-options.php
> Clarify received types in and around `::element_markup()`

- php/context/class-fieldmanager-context-storable.php
- tests/php/test-fieldmanager-select-field.php
Refines #686, the original Pull Request addressing the original report in #685, and expands it to address the same issue with checkboxes as reported in #764.
The differences between this and #686:
- Apply the fix only when `false === $serialize_data`, since both of the reports specify that the bug applies to those fields. Also, otherwise, we could inadvertently save a value for `$data` that only contained a few of the fields in a  group.
- Check whether the field exists in `$data` with `array_key_exists()` rather than `isset()`. The idea is that this expands backwards compatibility by contracting the number of cases when the new fallback value will be added to `$data`.
- Define `$data = array()` only when the field is a group, again to expand backwards compatibility by contracting the …
> Handle options fields in groups missing from `$_POST`

- tests/php/test-fieldmanager-script-loading.php
> Remove 'grid' from tested scripts

- js/fieldmanager-loader.js
This is a followup to 754f101 (#815) that adds spaces inside parenthesis.
> Make parenthesis spacing consistent

- fieldmanager.php
- package.json
Updates:
* Bumps version numbers
> Version 1.3.1 prep

- composer.json
> Updating semver for composer/installers.

- fieldmanager.php
- package.json
> version 1.6.1
